<?xml version="1.0"?>
<package format="3">
  <name>bladder_rtabmapper</name>
  <version>0.0.1</version>
  <description>RTAB-Map bringup external odometry node (C++)</description>
  <maintainer email="edoardo1.guida@mail.polimi.it">Guida Edoardo</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>rclcpp</depend>
  <depend>tf2_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rtabmap_ros</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>