camera_transform:
  # Static transform from wrist_3_link to camera
  translation:
    x: -0.00534
    y: 0.37727
    z: 0.21681
  rotation:
    x: 3.1416
    y: 0.0
    z: 2.0944  # 30 degrees in radians to point to where the camera sees
  parent_frame: "tool0"
  child_frame: "camera"