camera_transform:
  # Static transform from wrist_3_link to camera
  translation:
    x: -0.00815
    y: 0.33528
    z: 0.22184
  rotation:
    x: 0.0
    y: 0.0
    z: 4.18879  # 30 degrees in radians to point to where the camera sees ho un offset di 60 gradi dallásse perpendicolare alléndoscopio.
  parent_frame: "wrist_3_link"
  child_frame: "camera"